spring: 
    profiles:
        active:
        - dev
---
spring: 
    profiles: dev #开发环境
    application: 
        name: cloudstudy-dept
---
spring:
    profiles: test #测试环境
    application: 
        name: cloudstudy-dept
        #一定要保存为utf-8的格式